[chttpd]
bind_address = any
port = 5984
require_valid_user = true
enable_cors = true
max_http_request_size = 4294967296

[httpd]
enable_cors = true
bind_address = any
WWW-Authenticate = Basic realm="couchdb"

[cors]
# app://obsidian.md = Obsidian Desktop
# capacitor://localhost = Obsidian iOS/Android
# http://localhost = lokale Entwicklung
origins = app://obsidian.md,capacitor://localhost,http://localhost
credentials = true
headers = accept, authorization, content-type, origin, referer
methods = GET, PUT, POST, HEAD, DELETE, OPTIONS

[chttpd_auth]
require_valid_user = true

[couchdb]
single_node = true
